export const studiosData = [
  {
    id: 1,
    name: "The Atelier",
    location: "Shoreditch",
    fullLocation: "12 Rivington Street, Shoreditch, London EC2A 3DT",
    price: "Inquire",
    size: 450,
    beds: 1,
    baths: 1,
    type: "Loft",
    category: "industrial",
    featured: true,
    available: "Immediate",
    description:
      "An industrial masterpiece combining raw architectural elements with refined modern living. Soaring 15-foot ceilings, exposed steel beams, and original brick walls create a dramatic backdrop for contemporary urban life.",
    longDescription:
      "This exceptional loft studio represents the pinnacle of industrial-chic living in East London. Originally part of a Victorian textile factory, the space has been meticulously transformed while preserving its authentic character. The open-plan layout maximizes the dramatic ceiling height, while oversized steel-framed windows flood the interior with natural light throughout the day. Premium concrete flooring provides both aesthetic appeal and practical durability. The custom-designed mezzanine adds versatility, perfect for a bedroom or home office. State-of-the-art climate control and acoustic insulation ensure year-round comfort, while the location places you at the heart of London's most creative neighborhood.",
    features: [
      "Smart Home System",
      "Exposed Brick",
      "Steel Beams",
      "Concrete Floors",
      "Mezzanine Level",
      "Floor-to-ceiling Windows",
    ],
    amenities: [
      "High-speed Fiber",
      "Climate Control",
      "Security System",
      "Bike Storage",
    ],
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1515263487990-61b07816b324?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1600&h=1200&fit=crop",
    ],
  },
  {
    id: 2,
    name: "River Residency",
    location: "Canary Wharf",
    fullLocation: "28 Marsh Wall, Canary Wharf, London E14 9TP",
    price: "Inquire",
    size: 380,
    beds: 1,
    baths: 1,
    type: "Modern",
    category: "minimalist",
    featured: true,
    available: "Feb 2024",
    description:
      "Minimalist luxury with breathtaking Thames views. This contemporary studio epitomizes refined urban living with premium finishes and intelligent space planning.",
    longDescription:
      "Perched on the 22nd floor, this stunning studio offers uninterrupted views across the River Thames and London's dynamic skyline. The interior showcases Japanese-inspired minimalism with a warm, sophisticated palette. Engineered oak flooring, integrated lighting systems, and handleless cabinetry create seamless visual flow. The compact kitchen features premium Miele appliances and Caesarstone countertops. Full-height glazing can be tinted electronically for privacy and climate control. The marble bathroom includes a rainfall shower and heated floors. Building amenities include a 24-hour concierge, residents' gym, and private cinema.",
    features: [
      "River Views",
      "Smart Glass",
      "Miele Appliances",
      "Marble Bath",
      "Oak Flooring",
      "Integrated Lighting",
    ],
    amenities: [
      "24/7 Concierge",
      "Residents Gym",
      "Private Cinema",
      "Rooftop Terrace",
    ],
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=1600&h=1200&fit=crop",
    ],
  },
  {
    id: 3,
    name: "Garden Oasis",
    location: "Notting Hill",
    fullLocation: "45 Portobello Road, Notting Hill, London W11 3DB",
    price: "Inquire",
    size: 520,
    beds: 1,
    baths: 1,
    type: "Garden",
    category: "luxury",
    featured: true,
    available: "Immediate",
    description:
      "A rare garden studio in prestigious Notting Hill. Private outdoor space meets elegant interior design in this exceptional ground-floor residence.",
    longDescription:
      "This unique ground-floor studio offers the rare luxury of a private garden in one of London's most sought-after postcodes. French doors open onto a beautifully landscaped patio and garden area, creating a seamless indoor-outdoor living experience. The interior features herringbone parquet flooring, decorative cornicing, and a working fireplace. The bespoke kitchen includes Smeg appliances and marble worktops. Custom built-in wardrobes maximize storage while maintaining the elegant aesthetic. The bathroom showcases Victorian-style fixtures with modern functionality. Period features blend harmoniously with contemporary comforts including underfloor heating and USB charging points throughout.",
    features: [
      "Private Garden",
      "French Doors",
      "Period Features",
      "Fireplace",
      "Herringbone Floors",
      "Custom Storage",
    ],
    amenities: [
      "Garden Access",
      "Period Building",
      "Bike Storage",
      "Residents Lounge",
    ],
    images: [
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1600&h=1200&fit=crop",
    ],
  },
  {
    id: 4,
    name: "Skyline Suite",
    location: "London Bridge",
    fullLocation: "The Shard, 32 London Bridge Street, London SE1 9SG",
    price: "Inquire",
    size: 500,
    beds: 1,
    baths: 1,
    type: "Penthouse",
    category: "luxury",
    featured: true,
    available: "Mar 2024",
    description:
      "Penthouse living at its finest. Panoramic city views from the 35th floor of London's most iconic building.",
    longDescription:
      "Experience London from a new perspective in this breathtaking penthouse studio. Floor-to-ceiling windows on three sides provide 270-degree views encompassing Tower Bridge, St Paul's Cathedral, and beyond. The interior is finished to the highest specification with Italian marble, brushed brass fixtures, and motorized blinds. The designer kitchen features Gaggenau appliances and a wine fridge. The spa-style bathroom includes a deep soaking tub positioned to enjoy the views. Smart home technology controls lighting, heating, and entertainment systems. Building services include a private residents' lounge, spa, and fine dining restaurant.",
    features: [
      "Panoramic Views",
      "Smart Home",
      "Gaggenau Kitchen",
      "Spa Bathroom",
      "Marble Finishes",
      "Wine Fridge",
    ],
    amenities: [
      "Private Lounge",
      "Spa Facilities",
      "Fine Dining",
      "Valet Parking",
    ],
    images: [
      "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&h=1200&fit=crop",
    ],
  },
  {
    id: 5,
    name: "Heritage Studio",
    location: "Covent Garden",
    fullLocation: "8 Neal's Yard, Covent Garden, London WC2H 9DP",
    price: "Inquire",
    size: 420,
    beds: 1,
    baths: 1,
    type: "Conversion",
    category: "industrial",
    featured: false,
    available: "Immediate",
    description:
      "Characterful warehouse conversion in the cultural heart of London. Original features meet contemporary design.",
    longDescription:
      "This stunning conversion showcases the best of London's architectural heritage. Set within a Grade II listed Victorian warehouse, the studio retains original cast iron columns, exposed brickwork, and large arched windows. Modern interventions include a sleek mezzanine level, contemporary kitchen with stainless steel appliances, and a luxurious bathroom with rainfall shower. The high ceilings and open layout create a loft-like atmosphere, while thoughtful lighting design highlights the building's historic features. Located steps from the Royal Opera House and surrounded by world-class dining and entertainment.",
    features: [
      "Listed Building",
      "Cast Iron Columns",
      "Arched Windows",
      "Mezzanine",
      "Heritage Features",
      "Modern Kitchen",
    ],
    amenities: [
      "Secure Entry",
      "Bike Storage",
      "Central Location",
      "Period Building",
    ],
    images: [
      "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1565183928294-7d22f2d8b633?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=1600&h=1200&fit=crop",
    ],
  },
  {
    id: 6,
    name: "Nordic Haven",
    location: "Camden",
    fullLocation: "155 Regent's Park Road, Camden, London NW1 8BB",
    price: "Inquire",
    size: 460,
    beds: 1,
    baths: 1,
    type: "Scandi",
    category: "minimalist",
    featured: false,
    available: "Immediate",
    description:
      "Scandinavian design principles create a serene sanctuary. Natural materials, abundant light, and thoughtful details.",
    longDescription:
      "Embrace Nordic living in this beautifully designed studio that exemplifies Scandinavian simplicity and functionality. Whitewashed oak floors, soft grey walls, and abundant natural light create a calm, welcoming atmosphere. The open-plan layout incorporates clever storage solutions that maintain clean lines and uncluttered spaces. The kitchen features handleless cabinetry in matte white with integrated appliances. Large windows on two aspects ensure excellent daylight, complemented by a sophisticated lighting scheme for cozy evenings. The bathroom includes underfloor heating and premium fittings. Eco-friendly materials and energy-efficient systems reflect sustainable design principles.",
    features: [
      "Oak Flooring",
      "Dual Aspect",
      "Eco-Friendly",
      "Underfloor Heating",
      "Integrated Storage",
      "Natural Light",
    ],
    amenities: [
      "Bike Storage",
      "Communal Garden",
      "Green Building",
      "Package Room",
    ],
    images: [
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=1600&h=1200&fit=crop",
      "https://images.unsplash.com/photo-1615875221248-e7278eeff406?w=1600&h=1200&fit=crop",
    ],
  },
];
